import{S as u,a as d,i as l}from"./assets/vendor-BfwHKs76.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const o of t.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&n(o)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const p=document.querySelector("#search-form"),c=document.querySelector(".gallery"),f=document.querySelector("#loader");function g(){f.classList.remove("loader-hidden")}function m(){f.classList.add("loader-hidden")}const h="23458422-3da75be814240b3b99c5452e1",b="https://pixabay.com/api/",y=new u(".gallery a",{captionsData:"alt",captionDelay:250});p.addEventListener("submit",async a=>{a.preventDefault();const s=a.target.searchQuery.value.trim();if(s){c.innerHTML="",g();try{const{data:i}=await d.get(b,{params:{key:h,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0}});if(i.hits.length===0){l.warning({title:"Oops!",titleColor:"#fff",iconUrl:"./img/icon.svg",iconColor:"#fff",messageColor:"#fff",backgroundColor:"#ef4040",progressBarColor:"#b51b1b",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",close:!0,timeout:5e3,onOpening:(e,t)=>{const o=t.querySelector(".iziToast-close");if(o){o.innerHTML="";const r=document.createElementNS("http://www.w3.org/2000/svg","svg");r.setAttribute("xmlns","http://www.w3.org/2000/svg"),r.setAttribute("width","20"),r.setAttribute("height","20"),r.setAttribute("viewBox","0 0 24 24"),r.setAttribute("fill","#fafafb"),r.innerHTML=`
        <path d="M18.3 5.71a1 1 0 0 0-1.41 0L12 10.59 7.11 5.7A1 1 0 0 0 5.7 7.11L10.59 12l-4.89 4.89a1 1 0 1 0 1.41 1.41L12 13.41l4.89 4.89a1 1 0 0 0 1.41-1.41L13.41 12l4.89-4.89a1 1 0 0 0 0-1.4z"/>
      `,r.style.cursor="pointer",o.appendChild(r)}}});return}const n=i.hits.map(e=>`
        <a href="${e.largeImageURL}" class="photo-card">
          <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
          <div class="info">
            <p><b>Likes</b> ${e.likes}</p>
            <p><b>Views</b> ${e.views}</p>
            <p><b>Comments</b> ${e.comments}</p>
            <p><b>Downloads</b> ${e.downloads}</p>
          </div>
        </a>
      `).join("");c.insertAdjacentHTML("beforeend",n),y.refresh()}catch{l.error({title:"Error",titleColor:"#fff",iconUrl:"./img/icon.svg",iconColor:"#fff",messageColor:"#fff",backgroundColor:"#ef4040",progressBarColor:"#b51b1b",message:"Something went wrong while fetching images.",position:"topRight",close:!0,timeout:5e3,onOpening:(n,e)=>{const t=e.querySelector(".iziToast-close");if(t){t.innerHTML="";const o=document.createElementNS("http://www.w3.org/2000/svg","svg");o.setAttribute("xmlns","http://www.w3.org/2000/svg"),o.setAttribute("width","20"),o.setAttribute("height","20"),o.setAttribute("viewBox","0 0 24 24"),o.setAttribute("fill","#fafafb"),o.innerHTML=`
        <path d="M18.3 5.71a1 1 0 0 0-1.41 0L12 10.59 7.11 5.7A1 1 0 0 0 5.7 7.11L10.59 12l-4.89 4.89a1 1 0 1 0 1.41 1.41L12 13.41l4.89 4.89a1 1 0 0 0 1.41-1.41L13.41 12l4.89-4.89a1 1 0 0 0 0-1.4z"/>
      `,o.style.cursor="pointer",t.appendChild(o)}}})}finally{m()}}});
//# sourceMappingURL=index.js.map
